# Generated by Django 3.0.4 on 2020-04-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamverde_app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
