# Generated by Django 3.0.4 on 2020-04-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamverde_app', '0003_user_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.CreateModel(
            name='PeliculaCategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.Categoria')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.Pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=2000, null=True)),
                ('fechahora', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.Pelicula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='steamverde_app.User')),
            ],
        ),
    ]
