# Generated by Django 3.0.4 on 2020-04-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamverde_app', '0004_auto_20200422_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
